project:
  type: website

website:
  title: "Qualitative Data Analysis"
  sidebar:
    style: "floating"
    contents: "auto"

format:
  html:
    theme:
      - flatly
      - brand
    css: style.scss
    toc: true



